Milestone friendshipv1
Kyle-Law/ror-stay-in-touch pull request #2
Opened 2020-08-10 18:39 UTC by Kyle-Law

Good day! Friendship linkage have been set up. You can test the app by following steps:

- clone the branch
- bundle install
- rails db:seed
- sign in to your account
- Click all user
- when you clicked add friend, it'll show 'pending request', and you'll be able to accept or reject the invitation by going into the user page. (For the ease of experiment, the functionality be authorized later)
- Upon accepted, it'll show 'already friend' in all users step
- Upon rejected, 'Add friend' will be available again.

Thank you for reviewing. :)

2020-08-11 05:47 UTC, wathigo requested changes
### Changes Required.
Great work @Kyle-Law :clap: 
Let's make some changes in order to meet all the requirements.
Currently, our application does not allow us to accept or decline a friendship. Instead, we can be able to send a friend request to a user who is a pending friend.

**REQUIRED.**
* Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from Pathwright).
* User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from Pathwright).
* User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).
* User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-08-11 05:47 UTC, wathigo commented on app/models/friendship.rb
> +  # has_many :inverse_friends, through: :friendships, source: :user
Let's move the commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from Pathwright)

2020-08-11 05:47 UTC, wathigo commented on app/models/friendship.rb
> +  # end
Let's move the commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from Pathwright)

2020-08-11 05:47 UTC, wathigo commented on app/views/users/index.html.erb
> +          <% elsif current_user == user%>
**REQUIRED**
Let's remove all the logic from the views. Views related logic should be placed in the helpers. 
[The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

2020-08-11 11:18 UTC, Kyle-Law commented
Good day! Thanks for reviewing my project and the following refinement have been done:

- Unnecessary comments are removed
- View logics are moved to the helper
- Added Dark-Light Mode toggle
- Only friends' and user's posts are shown on the timeline
- Friendship requests can be rejected or accepted on individual user #show page

Thanks and looking forward to another review :)

* you may seed user by running `rails db:seed`

2020-08-11 15:16 UTC, Kyle-Law commented
Good day! Thanks for reviewing my project and the following refinement have been done:

- Unnecessary comments are removed
- View logics are moved to the helper
- Added Dark-Light Mode toggle
- Only friends' and user's posts are shown on the timeline
- Friendship requests can be rejected or accepted on individual user #show page

Thanks and looking forward to another review :)

* You may check the live version here: https://social-media-kyle.herokuapp.com/ (However, the dark-light toggling will only work upon refresh, probably because the javascript file will be re-run again upon clicking different links. The dark & light state will preserve in local storage hence feel free to refresh and try the functionality.)
* The javascript works well locally but not on heroku, feel free to shed some light on that matter.

2020-08-12 01:17 UTC, stratospherique requested changes
### Great Progress @Kyle-Law :clap: However, some requirements need to be implemented in order to get approval for this milestone. check :arrow_down: 

- **[REQUIRED]** Some of the requirements mentioned by the previous reviewer weren't implemented.
* [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
  - The invite button should hide for users that the current_user has a pending friend request with. Because otherwise, it will create duplicate friendships records and cause unexpected behaviour. In short, user shouldn't be able to send a friend request to users that he have pending friend request with.
* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- **[REQUIRED]** Pull request should display passing  code linter checks :heavy_check_mark: 

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-08-12 09:24 UTC, Kyle-Law commented
Thanks for reviewing. The functionality can be verified at https://social-media-kyle.herokuapp.com/

- To add friend, go to All user page, > click add friend > 'pending request' will be shown > go to the user page by click the user name > click accept > back to user page > 'Already Friend' will be shown > If rejected is selected, the request will be destroy and 'Add Friend' is possible again.
- Rubocop has been setup but doesn't show in PR. When I run 'rubocop .','31 files inspected, no offenses detected' detected is shown.

2020-08-12 21:05 UTC, jofer86 approved these changes
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- The required changes were made! good job!! You may pass!!
## `const PROJECT_STATUS = 'Approved'` 🚀 🚀 🚀
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-08-13 00:47 UTC, merged